### ISSUE TITLE
Userstory 1

### ISSUE THREAD

**Issue by HosseinKrouna** [HosseinKrouna/capstone-project#1]
## Value Proposition

**As aI User would like to see at a glance 
which events are taking place, 
who is there and who is not, 
and I also have the option 
of creating an entry.

**I want to** I want to view and select entries and possibility to create new entries

**so that**  I immediately have 
an overview of all upcoming events

## Description

<img width="356" alt="Screenshot 2023-01-19 at 12 48 24" src="https://user-images.githubusercontent.com/117902132/213435549-9bfb944a-9352-4c50-a922-11d40208bedf.png">

## Acceptance Criteria

- [ ] Show members next to the profileimage
- [ ] Always show profile picture
- [ ] Always show date
- [ ] Overview of the planned event-cards
- [ ] Show status of members in cards
- [ ] Button to create
- [ ] Homebutton

## Tasks
- [ ] Header-Component anlegen
          -> Profile Image
          -> Members Images
          -> Date display
- [ ] Card-Component
    {title, Date:{Date, time } , location, members}
-[ ] Button for create Date 
-[ ] Footer-Component
         -> HomeButton
-[ ] use Next.js App
-[ ] use Image from next/Image
-[ ] display on iphone SE gen 2

## Complexity

L

**Comment by RobinWitt** [comment]
Hey, the overall structure of your first user story is very good. 
However, in my opinion its a lot of tasks for just one user story. 
You might consider splitting it up. Since we have to get some more experience on how big user stories should be, I'm going to approve it anyway. Have a nice day!

**Comment by HosseinKrouna** [comment]
Hey thanks, good hint. 
I will include the create and home buttons in a later user story.
Best regards

**Comment by shebtastic** [comment]
Hi Hossein,
great work on your user story! 💪 We have a couple remarks:

**Value Proposition**
- the `**` seem to be remnants of broken markdown styling
- the value proposition does not entirely adhere to the given structure
  - the following can be shortened and worked into the **so that** part of the value proposition:
    > would like to see at a glance
    > which events are taking place,
    > who is there and who is not.
  - selection might not be part of this first story

**Description**
- are the members next to the profile necessary for this specific feature?
- is the profile picture necessary for this specific feature?
- the down arrow seems to indicate a scrolling action. we only want to show actual elements of the application. if you want to indicate scrolling in your wireframes, maybe have two frames with different scroll positions withe a scroll arrow between them. you could also describe the action in additional text or omit it completely, since overflow scrolling is the default browser behaviour.

**Tasks**
- the header component seems to have nested tasks. you can write those as markdown if you do
  ```md
  - [ ] `Header`-Component
    - [ ] Profile Image
  ```
- the card signature `{title, Date:{Date, time } , location, members}` does not look like valid syntax. you could correct the syntax or just list your expected prop names and give some prop value examples or types if you already thought about those.
- you can omit `use Next.js App` because our templates are all next.js based 😁
- `display on iphone SE gen 2` would be better as an acceptance criteria, but since this criteria is true for all of our tasks and stories, you don't have to explicitly mention it. that is up to you.

Your user story would benefit from a short title in addition to the user story number.

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by HosseinKrouna** [comment]
Thank you very much, I have now made the changes 😊

**Comment by mbosselmann** [comment]
Hi Hossein,
good job! 👍  Your user story looks good to me. Only some small remarks for your tasks are left now:
- Instead of writing "Use static data from /db.json/ with following props:
{title, startTime, endTime, location}" you could write "Use static data from /db.json/ with following keys: title, startTime, endTime, location"
- I don't understand "CSS - center it". Can you describe what you mean? 🤔

**Comment by HosseinKrouna** [comment]
Thank you Mareike. I leave out the css. I wanted to specify that the list should be centered

**Comment by F-Kirchhoff** [comment]
Hey Hossein, 
this is looking much better! Great improvements. Can you please give more details in your tasks? What kinds of components are you going to create? How do you plan to create the cards from the json? (Have a look at the recap projects, we provide a detailed list of tasks there).

**Comment by HosseinKrouna** [comment]
Thank you Felix for these good hints. I have now made the change

**Comment by F-Kirchhoff** [comment]
Amazing, I like it very much now. LGTM 🦊
