### ISSUE TITLE
Location Page

### ISSUE THREAD

**Issue by HosseinKrouna** [HosseinKrouna/capstone-project#16]
## Value Proposition

**As a** User
**I want to** locate by map
**so that** you can set markers on the map and have it displayed on the map by searching for an address 

## Description

![userstory_location-by-map](https://github.com/HosseinKrouna/capstone-project/assets/117902132/9f4aa8f9-89f8-425c-aa33-8765d2e3e7a9)

## Acceptance Criteria

- [ ] After a click on the text field "Location" you get to the location page.
- [ ] Markers can be used on the prospectus page to set the location either on the map or by entering the address.
- [ ] After confirming the location, you will return to the creation page and see the selected location in the map window.
- [ ] With the Submit button, a new event card is integrated into the indexeddb and generated with a selection of data from the database on the homepage in the event list.
- [ ] The event cards contain the title, start and end time, the voting result, an image, the location in as text and a small map.

## Tasks

- [ ] Install Leaflet
- [ ] Map component with the content:
  - [ ] Map
  - [ ] Address search bar
  - [ ] Correct address displayed
- [ ] A confirmation button thats redirects back

## Complexity

L
