### ISSUE TITLE
Userstory 2

### ISSUE THREAD

**Issue by HosseinKrouna** [HosseinKrouna/capstone-project#2]
## Value Proposition

**As a** I would like see my selected event and be able to see who is already there or who has cancelled
**I want to** I want to see the status of the event 
**so that** I have an overview of my selected event

## Description

<img width="337" alt="Screenshot 2023-01-19 at 15 53 02" src="https://user-images.githubusercontent.com/117902132/213475451-fda727f1-b493-4eb5-81ac-d9ab62809a7d.png">

## Acceptance Criteria

- [ ] Show selected event
- [ ] Show member status
 - [ ] Button "Yes"
 - [ ] Button "Maybe"
 - [ ] Button "No"
 - [ ] Homebutton

## Tasks

- [ ] selected card-event component
- [ ] Footer-Component
       -> HomeButton
- [ ] use Next.js App
- [ ] use Image from next/Image
- [ ] display on iphone SE gen 2

## Complexity

L

**Comment by niklasrammelkamp** [comment]
Hi Hussein, nice small User Story. 
But I honestly don't see any advantage in this story for the user. On the details page, you see the same information as on the list page. Maybe you wanna add some more information to the details page, that isn't necessary on the list page.

**Comment by mbosselmann** [comment]
Hi Hossein,
good job! 👍 I have some remarks:

- I agree to @niklasrammelkamp that you do not see further information on your details page. You should show this in your wireframe and describe this in your acceptance criteria.

**Description**
- The frame that surrounds your wireframes is confusing as these look similar to a mobile device. 😅 
- Currently it is also not possible to go back to the list view. I think that would be nice for the user and should be part of this user story.

**Acceptance Criteria**
- "appear" could be a misleading verb because that could imply that you want to insert the content with an animation
- it may be better to describe it like this:
- "On the details page the following information of one event are displayed:"
   - "The title of the event is displayed"
   - "The start time of the event is displayed"
   - And so on ;)

**Tasks**
- "Add a cklick event to the events list": There is a typo. And I think that you will work with a link and not with an onClick event maybe. :)
- "continue the click event here" What do you mean with this task? 🤔 

Feel free to ask me if you have further questions. :)

**Comment by RobinWitt** [comment]
I agree with the comments above that there is not really value for the user to have a details page if there is no additional information to see. You might want to think about what information you can add to the details page or take away from the overview page...

**Comment by HosseinKrouna** [comment]
First of all thanks for the review. I don't quite understand what the problem with the user story is. I can select an event and initially only see this one event on an extra page. with the home button i get back to the list. in the next user story, the user can then vote for the event. Why can't I just continue here?

**Comment by RobinWitt** [comment]
Since we don't know from here what is happening in your next user story, I can only decide on this isolated user story.
And when I think about clicking on an event/button in an app and I don't see more details than I saw on the overview, it doesn't make much sense to me.
My suggestion:
Overview Page shows only the title and the starting date of the event, Details Page shows the rest. If you add more details later, that's even better. You could still refactor that later when you have more information to display (or not display).
However, if you strongly feel to just continue then you should do that.
I still hope these suggestions where somewhat helpful.

**Comment by HosseinKrouna** [comment]
I think I didn't understand the task of a details page. Thanks for the lesson 😅. I hope I was able to give a little extra benefit with the change.

**Comment by RobinWitt** [comment]
Sorry if my tone was a bit too harsh. Looks good to me now!
