### ISSUE TITLE
Userstory 3 - Vote-component

### ISSUE THREAD

**Issue by HosseinKrouna** [HosseinKrouna/capstone-project#3]
## Value Proposition

**As a** User
**I want to** vote the event
**so that** I can share my decision 

## Description
<img width="203" alt="Screenshot 2023-01-20 at 11 29 04" src="https://user-images.githubusercontent.com/117902132/213673945-ee0d0a40-4b88-4e2a-bcc5-4dbb05e5bbde.png">

## Acceptance Criteria

- [ ] Show voting buttons
- [ ] The voting buttons should be toggleable

## Tasks

- [ ] Create vote-component
   - [ ] Button "Yes"
   - [ ] Button "Maybe"
   - [ ] Button "No"
   - [ ] Labelling all votes on the detailed view
 

## Complexity

S
