### ISSUE TITLE
Userstory #4 - Event Form

### ISSUE THREAD

**Issue by HosseinKrouna** [HosseinKrouna/capstone-project#6]
## Value Proposition

**As a** user
**I want** to create a new event
**so that** the created event will be added to the events list

## Description

<img width="798" alt="Screenshot 2023-01-25 at 16 01 58" src="https://user-images.githubusercontent.com/117902132/214598085-640a84df-34d4-43ed-a94f-717eb3fa18c0.png">

## Acceptance Criteria

- [ ] A link to the creationpage is displayed on the main page
- [ ] A backlink on the creationpage is displayed and redirects back to the homepage
- [ ] A titlename is displayed on top
- [ ] The title input is displayed
- [ ] The start time input is displayed
- [ ] The end time input is displayed
- [ ] The location input is displayed
- [ ] The creator input is displayed
- [ ] A submit button is displayed on the bottom of the page
- [ ] After clicking on the submit button, a new event is created in the event list and the user is redirected to the homepage

## Tasks

- [ ] Use localStorage hook
- [ ] Convert the JSON file to a helpers/lib file
- [ ] Create a Link component for the creationpage and back link
- [ ] Create a form component and render all input fields
  - [ ] The submit button inside the form element, which is expecting a "onSubmit" prop
  - [ ] Add the "onSubmit" prop as the callback function for the submit event of the form
-[ ] Add a creationfolder for the creationpage
  - [ ] Use the form component for rendering the input fields
    - [ ] Write a handleSubmit function which expects a submit event object
- [ ] Create a new event based on the transmitted data in the helpers file
- [ ] In the handleSubmit function, reroute the user to the main page after the submit

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by Olga-Mishareva** [comment]
Hi Hossein, LGTM :)
