### ISSUE TITLE
Edit Page - UserStory #5 

### ISSUE THREAD

**Issue by HosseinKrouna** [HosseinKrouna/capstone-project#9]
## Value Proposition

**As a** User
**I want to** be able to edit events
**so that** I can select, change and delete an event. My changes can be seen in the events list

## Description

<img width="1194" alt="Screenshot 2023-02-07 at 13 01 49" src="https://user-images.githubusercontent.com/117902132/217239864-20d4f034-527f-4bd9-94ef-3084ec667e5e.png">

## Acceptance Criteria

- [ ] Show the edit link in the events entry
- [ ] In the homepage, add an add button to create a new event
- [ ] See the voting results at all events
- [ ] In the edit page, show all input fields and requirements for changing information
- [ ] In the editpage, show the delete button that deletes the selected event from the list and redirects to the homepage
- [ ] With a backlink on every page, except the homepage, you can go back to the homepage
- [ ] In the edit page, the changes can be accepted with the submit button and bring back to the homepage with the events list

## Tasks

- [ ] Create a Link component for the "Edit Page" 
- [ ] Write a condition for the edit- and createpage, depending on whether a new event is to be create or modified
- [ ] Add the "onSubmit" prop as the callback function for the submit event of the form
- [ ] Write an onClick function that deletes the entry and reroute the user to the homepage.
- [ ] In the handleSubmit function, reroute the user to the homepage after submit

## Complexity

XL

**Comment by AstridOttmann** [comment]
Hey :-)
your wireframe is a bit confusing, I suppose everything what is coloured green is content of this US? 

I think you would do yourself a favour to reduce the complexity a little bit, i. e. handling the delete in another US or the votes page. 
Maybe you concentrate an the edit page and the links (just a suggestion ;-))

My suggestion for a more clear value proposition: 
As a User
I want to be able to edit my events,
so that I can adapt and update my entries

Tasks: 
- "Write a condition for the edit- and createpage, depending on whether a new event is to be create or modified" - 
what do you mean? Using the form component for both cases conditionally rendering the form?

Especially when it's so complex, you might be more descriptive in your tasks. 
- "See the voting results at all events"  - for this feature I can't find anything in the tasks?
- "Create a Link component for the "Edit Page" - only for the edit page? 

Sorry, this was a lot :-( 
if you want I can take a look at your changes later on
​

**Comment by HosseinKrouna** [comment]
Good morning Astrid, 
thank you very much for your remarks and the offer to take a look at the changes. 

Now I can see the confusion more clearly😌. You are not wrong at all. Most of these are legitimate. I will change it again.

**Comment by marcterre** [comment]
Hey Hossein, if you already implement the voting results you dont have to mention them here. Also cut it out of the wireframe. You can hardly read something on them 😅
As Astrid mentioned you should move the delete functionality in another user story. It seems a little bit to much.
Feel free to ask 👍

**Comment by marcterre** [comment]
We talked about the changes personally 👍
